final List<String> medications = <String>[
  Abiraterone,
  Alemtuzumab,
  Anastrozole,
  Aprepitant,
  Arsenic trioxide,
  Atezolizumab,
  Azacitidine,
  Bevacizumab,
  Bleomycin,
  Bortezomib,
  Cabazitaxel,
  Capecitabine,
  Carboplatin,
  Cetuximab,
  Chemotherapy drug combinations,
  Cisplatin,
  Crizotinib,
  Cyclophosphamide,
  Cytarabine,
];