final List<String> symptoms = <String>[
  'blurry vision',
  'chills',
  'difficulty sleeping',
  'dizziness',
  'fainting',
  'fatigue',
  'fever',
  'headache',
  'loss of appetite',
  'nauseau',
  'pain',
  'rashes',
  'shortness of breath',
  'tremors',
  'vomiting',
  'weakness',
];
